#############################################################################
# Makefile for building: harmonies_qt
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  HarmoniesQt.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile HarmoniesQt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = harmonies_qt1.0.0
DISTDIR = /home/batyass/Projects/LO21projet/.tmp/harmonies_qt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -pipe -O2 -std=gnu++11 -flto=8 -fno-fat-lto-objects -fuse-linker-plugin -fPIC
LIBS          = $(SUBLIBS) /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/qt/main_qt.cpp \
		src/ui/qt/GameControllerQt.cpp \
		src/ui/qt/MainWindow.cpp \
		src/core/AnimalCubePlacementService.cpp \
		src/core/DefaultDeckFactory.cpp \
		src/core/Game.cpp \
		src/core/NatureSpiritPlacementService.cpp \
		src/core/SlotSelectionService.cpp \
		src/core/TokenPlacementService.cpp \
		src/core/TurnManager.cpp \
		src/model/AnimalCard.cpp \
		src/model/AnimalCardDeck.cpp \
		src/model/BoardCell.cpp \
		src/model/CentralBoard.cpp \
		src/model/GameConfig.cpp \
		src/model/NatureSpiritCard.cpp \
		src/model/NatureSpiritDeck.cpp \
		src/model/Pattern.cpp \
		src/model/PersonalBoard.cpp \
		src/model/Player.cpp \
		src/model/PlayerCardCollection.cpp \
		src/model/ScoreReport.cpp \
		src/model/TokenBag.cpp \
		src/model/TokenSlot.cpp \
		src/rules/EndGameChecker.cpp \
		src/rules/PatternMatcher.cpp \
		src/rules/PlacementValidator.cpp \
		src/rules/StackRule.cpp \
		src/scoring/AnimalCardScoreCalculator.cpp \
		src/scoring/LandscapeScoreCalculator.cpp \
		src/scoring/NatureSpiritScoreCalculator.cpp \
		src/scoring/ScoreCalculator.cpp \
		src/scoring/SoloScoreEvaluator.cpp \
		src/ui/qt/SetupWindow.cpp \
		src/utils/hexCoord.cpp moc_SetupWindow.cpp
OBJECTS       = main_qt.o \
		GameControllerQt.o \
		MainWindow.o \
		AnimalCubePlacementService.o \
		DefaultDeckFactory.o \
		Game.o \
		NatureSpiritPlacementService.o \
		SlotSelectionService.o \
		TokenPlacementService.o \
		TurnManager.o \
		AnimalCard.o \
		AnimalCardDeck.o \
		BoardCell.o \
		CentralBoard.o \
		GameConfig.o \
		NatureSpiritCard.o \
		NatureSpiritDeck.o \
		Pattern.o \
		PersonalBoard.o \
		Player.o \
		PlayerCardCollection.o \
		ScoreReport.o \
		TokenBag.o \
		TokenSlot.o \
		EndGameChecker.o \
		PatternMatcher.o \
		PlacementValidator.o \
		StackRule.o \
		AnimalCardScoreCalculator.o \
		LandscapeScoreCalculator.o \
		NatureSpiritScoreCalculator.o \
		ScoreCalculator.o \
		SoloScoreEvaluator.o \
		SetupWindow.o \
		hexCoord.o \
		moc_SetupWindow.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		HarmoniesQt.pro include/ui/qt/GameControllerQt.h \
		include/ui/qt/MainWindow.h \
		include/ui/qt/SetupWindow.h src/qt/main_qt.cpp \
		src/ui/qt/GameControllerQt.cpp \
		src/ui/qt/MainWindow.cpp \
		src/core/AnimalCubePlacementService.cpp \
		src/core/DefaultDeckFactory.cpp \
		src/core/Game.cpp \
		src/core/NatureSpiritPlacementService.cpp \
		src/core/SlotSelectionService.cpp \
		src/core/TokenPlacementService.cpp \
		src/core/TurnManager.cpp \
		src/model/AnimalCard.cpp \
		src/model/AnimalCardDeck.cpp \
		src/model/BoardCell.cpp \
		src/model/CentralBoard.cpp \
		src/model/GameConfig.cpp \
		src/model/NatureSpiritCard.cpp \
		src/model/NatureSpiritDeck.cpp \
		src/model/Pattern.cpp \
		src/model/PersonalBoard.cpp \
		src/model/Player.cpp \
		src/model/PlayerCardCollection.cpp \
		src/model/ScoreReport.cpp \
		src/model/TokenBag.cpp \
		src/model/TokenSlot.cpp \
		src/rules/EndGameChecker.cpp \
		src/rules/PatternMatcher.cpp \
		src/rules/PlacementValidator.cpp \
		src/rules/StackRule.cpp \
		src/scoring/AnimalCardScoreCalculator.cpp \
		src/scoring/LandscapeScoreCalculator.cpp \
		src/scoring/NatureSpiritScoreCalculator.cpp \
		src/scoring/ScoreCalculator.cpp \
		src/scoring/SoloScoreEvaluator.cpp \
		src/ui/qt/SetupWindow.cpp \
		src/utils/hexCoord.cpp
QMAKE_TARGET  = harmonies_qt
DESTDIR       = 
TARGET        = harmonies_qt


first: all
####### Build rules

harmonies_qt:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HarmoniesQt.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		HarmoniesQt.pro
	$(QMAKE) -o Makefile HarmoniesQt.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
HarmoniesQt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile HarmoniesQt.pro

qmake_all: FORCE


all: Makefile harmonies_qt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/ui/qt/GameControllerQt.h include/ui/qt/MainWindow.h include/ui/qt/SetupWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/qt/main_qt.cpp src/ui/qt/GameControllerQt.cpp src/ui/qt/MainWindow.cpp src/core/AnimalCubePlacementService.cpp src/core/DefaultDeckFactory.cpp src/core/Game.cpp src/core/NatureSpiritPlacementService.cpp src/core/SlotSelectionService.cpp src/core/TokenPlacementService.cpp src/core/TurnManager.cpp src/model/AnimalCard.cpp src/model/AnimalCardDeck.cpp src/model/BoardCell.cpp src/model/CentralBoard.cpp src/model/GameConfig.cpp src/model/NatureSpiritCard.cpp src/model/NatureSpiritDeck.cpp src/model/Pattern.cpp src/model/PersonalBoard.cpp src/model/Player.cpp src/model/PlayerCardCollection.cpp src/model/ScoreReport.cpp src/model/TokenBag.cpp src/model/TokenSlot.cpp src/rules/EndGameChecker.cpp src/rules/PatternMatcher.cpp src/rules/PlacementValidator.cpp src/rules/StackRule.cpp src/scoring/AnimalCardScoreCalculator.cpp src/scoring/LandscapeScoreCalculator.cpp src/scoring/NatureSpiritScoreCalculator.cpp src/scoring/ScoreCalculator.cpp src/scoring/SoloScoreEvaluator.cpp src/ui/qt/SetupWindow.cpp src/utils/hexCoord.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -flto -fno-fat-lto-objects -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_SetupWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SetupWindow.cpp
moc_SetupWindow.cpp: include/ui/qt/SetupWindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/batyass/Projects/LO21projet/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/batyass/Projects/LO21projet -I/home/batyass/Projects/LO21projet/include -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include include/ui/qt/SetupWindow.h -o moc_SetupWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main_qt.o: src/qt/main_qt.cpp include/ui/qt/SetupWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_qt.o src/qt/main_qt.cpp

GameControllerQt.o: src/ui/qt/GameControllerQt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameControllerQt.o src/ui/qt/GameControllerQt.cpp

MainWindow.o: src/ui/qt/MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/ui/qt/MainWindow.cpp

AnimalCubePlacementService.o: src/core/AnimalCubePlacementService.cpp include/core/AnimalCubePlacementService.h \
		include/model/AnimalCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/rules/PatternMatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalCubePlacementService.o src/core/AnimalCubePlacementService.cpp

DefaultDeckFactory.o: src/core/DefaultDeckFactory.cpp include/core/DefaultDeckFactory.h \
		include/model/AnimalCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/model/NatureSpiritCard.h \
		include/scoring/NatureSpiritEffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DefaultDeckFactory.o src/core/DefaultDeckFactory.cpp

Game.o: src/core/Game.cpp include/core/Game.h \
		include/model/Player.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/model/PlayerCardCollection.h \
		include/model/AnimalCard.h \
		include/model/AnimalCardDeck.h \
		include/model/NatureSpiritDeck.h \
		include/model/GameConfig.h \
		include/model/TokenBag.h \
		include/model/CentralBoard.h \
		include/model/TokenSlot.h \
		include/core/TurnManager.h \
		include/core/GameState.h \
		include/core/TurnContext.h \
		include/core/NatureSpiritPlacementService.h \
		include/core/DefaultDeckFactory.h \
		include/rules/EndGameChecker.h \
		include/core/AnimalCubePlacementService.h \
		include/core/SlotSelectionService.h \
		include/core/TokenPlacementService.h \
		include/scoring/AnimalCardScoreCalculator.h \
		include/scoring/LandscapeScoreCalculator.h \
		include/model/StackType.h \
		include/rules/StackRule.h \
		include/scoring/NatureSpiritScoreCalculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o src/core/Game.cpp

NatureSpiritPlacementService.o: src/core/NatureSpiritPlacementService.cpp include/core/NatureSpiritPlacementService.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/rules/PatternMatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NatureSpiritPlacementService.o src/core/NatureSpiritPlacementService.cpp

SlotSelectionService.o: src/core/SlotSelectionService.cpp include/core/SlotSelectionService.h \
		include/model/CentralBoard.h \
		include/model/TokenSlot.h \
		include/model/TokenType.h \
		include/model/TokenBag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SlotSelectionService.o src/core/SlotSelectionService.cpp

TokenPlacementService.o: src/core/TokenPlacementService.cpp include/core/TokenPlacementService.h \
		include/utils/hexCoord.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/model/TokenType.h \
		include/rules/PlacementValidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TokenPlacementService.o src/core/TokenPlacementService.cpp

TurnManager.o: src/core/TurnManager.cpp include/core/TurnManager.h \
		include/model/Player.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/model/PlayerCardCollection.h \
		include/model/AnimalCard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TurnManager.o src/core/TurnManager.cpp

AnimalCard.o: src/model/AnimalCard.cpp include/model/AnimalCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalCard.o src/model/AnimalCard.cpp

AnimalCardDeck.o: src/model/AnimalCardDeck.cpp include/model/AnimalCardDeck.h \
		include/model/AnimalCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalCardDeck.o src/model/AnimalCardDeck.cpp

BoardCell.o: src/model/BoardCell.cpp include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BoardCell.o src/model/BoardCell.cpp

CentralBoard.o: src/model/CentralBoard.cpp include/model/CentralBoard.h \
		include/model/TokenSlot.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CentralBoard.o src/model/CentralBoard.cpp

GameConfig.o: src/model/GameConfig.cpp include/model/GameConfig.h \
		include/model/BoardSide.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameConfig.o src/model/GameConfig.cpp

NatureSpiritCard.o: src/model/NatureSpiritCard.cpp include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NatureSpiritCard.o src/model/NatureSpiritCard.cpp

NatureSpiritDeck.o: src/model/NatureSpiritDeck.cpp include/model/NatureSpiritDeck.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NatureSpiritDeck.o src/model/NatureSpiritDeck.cpp

Pattern.o: src/model/Pattern.cpp include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pattern.o src/model/Pattern.cpp

PersonalBoard.o: src/model/PersonalBoard.cpp include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PersonalBoard.o src/model/PersonalBoard.cpp

Player.o: src/model/Player.cpp include/model/Player.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/model/PlayerCardCollection.h \
		include/model/AnimalCard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o src/model/Player.cpp

PlayerCardCollection.o: src/model/PlayerCardCollection.cpp include/model/PlayerCardCollection.h \
		include/model/AnimalCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlayerCardCollection.o src/model/PlayerCardCollection.cpp

ScoreReport.o: src/model/ScoreReport.cpp include/model/ScoreReport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScoreReport.o src/model/ScoreReport.cpp

TokenBag.o: src/model/TokenBag.cpp include/model/TokenBag.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TokenBag.o src/model/TokenBag.cpp

TokenSlot.o: src/model/TokenSlot.cpp include/model/TokenSlot.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TokenSlot.o src/model/TokenSlot.cpp

EndGameChecker.o: src/rules/EndGameChecker.cpp include/rules/EndGameChecker.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/model/TokenBag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EndGameChecker.o src/rules/EndGameChecker.cpp

PatternMatcher.o: src/rules/PatternMatcher.cpp include/rules/PatternMatcher.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/model/Pattern.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PatternMatcher.o src/rules/PatternMatcher.cpp

PlacementValidator.o: src/rules/PlacementValidator.cpp include/rules/PlacementValidator.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlacementValidator.o src/rules/PlacementValidator.cpp

StackRule.o: src/rules/StackRule.cpp include/rules/StackRule.h \
		include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/model/StackType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StackRule.o src/rules/StackRule.cpp

AnimalCardScoreCalculator.o: src/scoring/AnimalCardScoreCalculator.cpp include/scoring/AnimalCardScoreCalculator.h \
		include/model/AnimalCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalCardScoreCalculator.o src/scoring/AnimalCardScoreCalculator.cpp

LandscapeScoreCalculator.o: src/scoring/LandscapeScoreCalculator.cpp include/scoring/LandscapeScoreCalculator.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/model/StackType.h \
		include/rules/StackRule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LandscapeScoreCalculator.o src/scoring/LandscapeScoreCalculator.cpp

NatureSpiritScoreCalculator.o: src/scoring/NatureSpiritScoreCalculator.cpp include/scoring/NatureSpiritScoreCalculator.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NatureSpiritScoreCalculator.o src/scoring/NatureSpiritScoreCalculator.cpp

ScoreCalculator.o: src/scoring/ScoreCalculator.cpp include/scoring/ScoreCalculator.h \
		include/model/Player.h \
		include/model/NatureSpiritCard.h \
		include/model/Pattern.h \
		include/utils/hexCoord.h \
		include/model/TokenType.h \
		include/scoring/NatureSpiritEffect.h \
		include/model/PersonalBoard.h \
		include/model/BoardSide.h \
		include/model/BoardCell.h \
		include/model/PlayerCardCollection.h \
		include/model/AnimalCard.h \
		include/model/ScoreReport.h \
		include/scoring/LandscapeScoreCalculator.h \
		include/model/StackType.h \
		include/rules/StackRule.h \
		include/scoring/AnimalCardScoreCalculator.h \
		include/scoring/NatureSpiritScoreCalculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScoreCalculator.o src/scoring/ScoreCalculator.cpp

SoloScoreEvaluator.o: src/scoring/SoloScoreEvaluator.cpp include/scoring/SoloScoreEvaluator.h \
		include/model/BoardSide.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoloScoreEvaluator.o src/scoring/SoloScoreEvaluator.cpp

SetupWindow.o: src/ui/qt/SetupWindow.cpp include/ui/qt/SetupWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SetupWindow.o src/ui/qt/SetupWindow.cpp

hexCoord.o: src/utils/hexCoord.cpp include/utils/hexCoord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hexCoord.o src/utils/hexCoord.cpp

moc_SetupWindow.o: moc_SetupWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SetupWindow.o moc_SetupWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

